/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Bee.glb --output src/app/components/BeeModel.jsx --overwrite 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/Bee.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tripo_node_f0d653f6.geometry} material={materials.tripo_mat_f0d653f6} rotation={[-Math.PI / 2 + 0.2, 0.15, Math.PI - 0.1]} />
    </group>
  )
}

useGLTF.preload('/models/Bee.glb')
